---
SERVER_IP: "192.168.1.29"
SERVER_PORT: 2237

MQTT_SERVER: "192.168.1.249"
MQTT_SERVER_PORT: 1883
BROKER_TOPIC: "wsjtx/dx"

MY_LOCATOR: "IO74"

BANDS:
  7074000:
    MIN_DX: 200
    ONLY_NEWCALL: True
  5031300:
    MIN_DX: 100
    ONLY_NEWCALL: False
  144174000:
    MIN_DX: 200
    ONLY_NEWCALL: True
    EXCLUDE_CALLSIGNS:
      - GI

