---
SERVER_IP: "192.168.1.29"
SERVER_PORT: 2237

MQTT_SERVER: "192.168.1.249"
MQTT_SERVER_PORT: 1883
BROKER_TOPIC: "wsjtx/dx"

FREQUENCIES:
  - 144174000
  - 7074000
  - 50313000

EXCLUDE_CALLSIGNS:
  - GI
